use_frameworks!

platform :ios, '9.0'

target 'LLReformerKeysKit_Example' do
  pod 'LLReformerKeysKit', :path => '../'

  target 'LLReformerKeysKit_Tests' do
    inherit! :search_paths

    
  end
end
